### ISSUE TITLE
Fatal error on URL generation

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#222]
From [sburn's review](https://wordpress.org/support/topic/fatal-6/):

A fatal error is produced when generating an LD-JSON script.
Seemingly, `remove_query_args()` isn't always available.

According to the topic tags, the error occurs on a multisite installation.

Backtrace:
```
[20-Nov-2017 15:21:20 UTC] PHP Fatal error: Uncaught Error: Call to undefined function remove_query_args() in /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/generate-url.class.php:665
Stack trace:
#0 /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/generate-url.class.php(92): The_SEO_Framework\Generate_Url->remove_pagination_from_url(‘http://orangeco…’)
#1 /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/generate-url.class.php(64): The_SEO_Framework\Generate_Url->get_canonical_url(Array)
#2 /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/render.class.php(96): The_SEO_Framework\Generate_Url->create_canonical_url(Array)
#3 /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/generate-ldjson.class.php(211): The_SEO_Framework\Render->get_homepage_permalink()
#4 /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/generate-ldjson.class.php(172): The_SEO_Framework\Generate_Ldjson->get in /home/somesite.com/www/wp-content/plugins/autodescription/inc/classes/generate-url.class.php on line 665
```

**Comment by sybrew** [comment]
This only happens when the user doesn't have pretty permalinks enabled.
